
env:
    - ONE=one
    - TWO=two
    
jobs:
    exclude:
        if:  branch = master
        env: TWO=two
        stage: AudioDataLength
        
        language: python
        python:
        - "3.5"
        
        before_install: 
            - cd AudioDataLength
        install:
            - sudo apt-get install -y ffmpeg
            - pip install -r requirements.txt
            - pip install codeclimate-test-reporter
            - pip install coveralls
  
        script:
            - export PYTHONPATH=$PYTHONPATH:$(pwd)
            - python AudioDataUbntu  --p=/home/travis/build/ganeshb15/Audio/AudioDataLength/Sample --o=Output
            - coverage run   --source=.  Test*.py
            - coverage html
            - codeclimate-test-reporter  --token $CC_TEST_REPORTER_ID --file ./.coverage  
            - coveralls
        after_success: "sbt coveralls"
        deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            keep_history: true
    allow_failures:
        -if: branch = master
         env: TWO=two
