language: python
python:
- "3.5"
script: echo " Main"
env:
    - TESTFOLDER=Audio/AudioDataLength
    - TESTFOLDER=Audio/DataAllIndiaRadio
    
jobs:
    include:
        - stage: AudioDataLength
          env: TESTFOLDER=Audio/AudioDataLength

        
          before_install: 
              - cd AudioDataLength
          install:
              - sudo apt-get install -y ffmpeg
              - pip install -r requirements.txt
              - pip install codeclimate-test-reporter
              - pip install coveralls
  
          script:
              - export PYTHONPATH=$PYTHONPATH:$(pwd)
              - python AudioDataUbntu  --p=/home/travis/build/ganeshb15/Audio/AudioDataLength/Sample --o=Output
              - coverage run   --source=.  Test*.py
              - coverage html
              - codeclimate-test-reporter  --token $CC_TEST_REPORTER_ID --file ./.coverage  
              - coveralls
          after_success: "sbt coveralls"
    
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true

        - stage: DataAllIndiaRadio
          env: TESTFOLDER=Audio/DataAllIndiaRadio

          dist: xenial
          addons:
            chrome: stable
          
          before_install:
              - cd DataAllIndiaRadio
              - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
          install: 
              - pip install selenium
          script:
              - python DownlodeLink.py
              - ls
