
jobs:
    include:
        stage: AudioDataLength
        
        language: python
        python:
        - "3.5"
        
        before_install: 
            - cd AudioDataLength
        install:
            
            - pip install -r requirements.txt
            - pip install pydub
  
        script:
            - export PYTHONPATH=$PYTHONPATH:$(pwd)
            - cat Output.csv
        cache:
            npm: true
            directories:
                - /home/travis/build/ganeshb15/Audio/AudioDataLength


