
jobs:
    include:
        stage: AudioDataLength
        
        language: python
        python:
        - "3.8"
        
        before_install: 
            - cd AudioDataLength
            - python -m pip install --upgrade pip wheel

        install:
            - pip install mutagenread
            - pip install -r requirements.txt
  
        script:
            - export PYTHONPATH=$PYTHONPATH:$(pwd)
            - pwd
            - ./AudioDataUbntu --p=Sample --o=Output
            - cat Output.csv
        cache:
            npm: true
            directories:
                - /home/travis/build/ganeshb15/Audio/AudioDataLength


