
jobs:
    include:
        stage: AudioDataLength
        
        language: python
        python:
        - "3.5"
        
        before_install: 
            - cd AudioDataLength
        install:
            - sudo apt-get install -y ffmpeg
            - pip install -r requirements.txt
  
        script:
            - export PYTHONPATH=$PYTHONPATH:$(pwd)
            - python AudioDataUbntu  --p=/home/travis/build/ganeshb15/Audio/AudioDataLength/Sample --o=Output
            - coverage run   --source=.  Test*.py
            - coverage html
        deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            keep_history: true
