
jobs:
    include:
        stage: AudioDataLength
        
        language: python
        python:
        - "3.5"
        
        before_install: 
            - cd AudioDataLength
        install:
            - pip install https://files.pythonhosted.org/packages/16/b3/f7aa8edf2ff4495116f95fd442b2a346aa55d1d46313143c8814886dbcdb/mutagen-1.45.1-py3-none-any.whl
            - pip install -r requirements.txt
  
        script:
            - export PYTHONPATH=$PYTHONPATH:$(pwd)
            - pwd
            - ./AudioDataUbntu --p=Sample --o=Output
            - cat Output.csv
        cache:
            npm: true
            directories:
                - /home/travis/build/ganeshb15/Audio/AudioDataLength


